f=open('test.txt','r')
c=f.readline()
print("1:%s"%c)
c2=f.readline()
print("2:%s"%c2)
c3=f.readline()
print("3:%s"%c3)
c4=f.readline()
print("4:%s"%c4)
c5=f.readline()
print("5:%s"%c5)
c6=f.readline()
print("6:%s"%c6)
f.close()

